name: Lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
      - name: Cache the dependencies
        run: deno cache mod.ts
      - name: Run format script with --check
        run: deno fmt --ignore=./docs --check
